# Use a Node base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
# This is done as a separate step to take advantage of Docker layer caching.
COPY package.json ./
RUN npm install

# The command to run the app will be specified in the docker-compose.dev.yml
